---
language: ruby
rvm:
  - 2.3
sudo: required

services:
  - docker

# matrix has to be populated by hand for now (https://github.com/travis-ci/travis-ci/issues/1519)
env:
  global:
    - PACKER_VERSION="1.1.3"
  matrix:
    - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-update-disabled"
    - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-update-enabled"
    - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-sshd"
    - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-networking"
    - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-vagrant"
    - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-cleanup"

jobs:
  include:
    - stage: Test Ansible roles installation
      before_install: sudo provisioning/scripts/install_ansible.sh
      script: test/scripts/ci/install-ansible-roles.sh
    - stage: Run Test-Kitchen
      before_install: sudo test/scripts/ci/before_install.sh
      install: test/scripts/ci/install.sh
      script: test/scripts/ci/script.sh
