---
language: ruby
rvm:
  - 2.3
sudo: required

services:
  - docker

env:
  - PACKER_VERSION="1.1.3"

before_install: sudo test/scripts/ci/before_install.sh
install:
  - test/scripts/ci/install.sh
  - sudo provisioning/scripts/install_ansible.sh
script: test/scripts/ci/script.sh
