---
language: ruby
rvm:
  - 2.3
sudo: required

services:
  - docker

# matrix has to be populated by hand for now (https://github.com/travis-ci/travis-ci/issues/1519)
env:
  - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-update-disabled"
  - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-update-enabled"
  - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-sshd"
  - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-networking"
  - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-vagrant"
  - KITCHEN_PLATFORM="ubuntu-1710" KITCHEN_SCRIPT="script-cleanup"

before_install: gem install bundle
install: bundle install
script: kitchen test "$KITCHEN_SCRIPT-$KITCHEN_PLATFORM"

jobs:
  include:
    - stage: validate packer template
      before_install: chmod a+x test/scripts/ci/install-packer.sh && sudo test/scripts/ci/install-packer.sh
      script: chmod a+x test/scripts/ci/validate-packer-template.sh && test/scripts/ci/validate-packer-template.sh
      env:
        - PACKER_VERSION="1.1.3"
    - stage: validate ansible role installation
      before_install: chmod a+x provisioning/scripts/install_ansible.sh && sudo provisioning/scripts/install_ansible.sh
      script: chmod a+x test/scripts/ci/install-ansible-roles.sh && test/scripts/ci/install-ansible-roles.sh

stages:
  - validate packer template
  - validate ansible role installation
  - test
