---
  - hosts: all
    gather_facts: yes
    roles:
      - role: geerlingguy.java
        ansible_distribution_version: "16.04"
        become: yes
        java_packages:
          - openjdk-8-jdk
      - role: ferrarimarco.eclipse
        become: yes
        java_openjdk_use_ppa: no
      - role: ferrarimarco.tomcat
        become: yes
