---
  - hosts: all
    gather_facts: yes
    pre_tasks:
      - name: Ensure required apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - apt-transport-https
          - bzip2
          - ca-certificates
          - curl
          - gzip
          - tar
          - unzip
      - name: Ensure additional apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - bmon
          - bridge-utils
          - chromium-browser
          - git
          - glogg
          - imagemagick
          - jmeter
          - libreoffice-calc
          - maven
          - nethogs
          - subversion
    roles:
      - role: infOpen.locales
        become: yes
      - role: ferrarimarco.nano
        become: yes
      - role: ferrarimarco.bash-aliases
        bash_aliases:
          - { alias: "changelog-generator", command: 'docker run -it --rm -v "$(pwd)":/app prooph/github-changelog-generator' }
          - { alias: "docker-clean", command: 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean' }
          - { alias: "dockerfile-lint", command: 'echo "Linting Dockerfiles from $(pwd)"; find . -type f -iname "Dockerfile" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm -w="/mnt" lukasmartinelli/hadolint hadolint "$line"; docker run -v "$(pwd)":/mnt --rm -w="/mnt" redcoolbeans/dockerlint "$line"; done' }
          - { alias: "git-log1", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg1' }
          - { alias: "git-log2", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg2' }
          - { alias: "git-log3", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg3' }
          - { alias: "psscriptanalyzer", command: 'docker run -it --rm -v "$(pwd)":/powershell cvent/psscriptanalyzer' }
          - { alias: "shellcheck", command: 'echo "Linting shell scripts from $(pwd)"; find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck-alpine "$line"; done'}
          - { alias: "pgadmin4", command: 'mkdir -p ~/.pgadmin4; name=pgadmin4; if [ ! "$(docker ps -q -f name=$name)" ]; then echo "Starting $name container"; docker run -d -p 5050:5050 -e "SERVER_MODE=False" --rm --name="$name" -v /home/vagrant/.pgadmin4:/data chorss/docker-pgadmin4; fi; sleep 5; xdg-open http://localhost:5050;'}
        become: yes
