---
  - hosts: all
    gather_facts: yes
    pre_tasks:
      - name: Ensure required apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - apt-transport-https
          - bzip2
          - ca-certificates
          - curl
          - gzip
          - language-pack-en
          - tar
          - unzip
      - name: Ensure additional apt packages are installed
        apt:
          autoremove: yes
          cache_valid_time: 3600
          pkg: "{{ item }}"
          state: present
          update_cache: yes
        become: yes
        with_items:
          - bmon
          - bridge-utils
          - chromium-browser
          - git
          - glogg
          - imagemagick
          - jmeter
          - libreoffice-calc
          - maven
          - nethogs
          - subversion
    post_tasks:
      - name: Upgrade pip before installing any other packages
        become: yes
        pip:
          name: "pip"
          version: "9.0.1"
      - name: Install pip packages
        become: yes
        pip:
          name: "{{item.name}}"
          version: "{{item.version}}"
        with_items:
          - { name: 'cookiecutter', version: '1.6.0' }
          - { name: 'sqlparse', version: '0.2.4' }
      - name: Add vagrant user to docker group
        become: yes
        user:
          groups: "docker"
          name: vagrant
      - name: Initialize Oracle SQL Developer
        copy:
          dest: /home/vagrant/.sqldeveloper/17.4.0/
          group: vagrant
          mode: 0664
          owner: vagrant
          src: files/.sqldeveloper/product.conf
      - name: Install JaspersoftStudio CE
        apt:
          deb: https://netcologne.dl.sourceforge.net/project/jasperstudio/JaspersoftStudio-6.5.1/TIB_js-studiocomm_6.5.1.final_linux_amd64.deb
        become: yes
    roles:
      - role: stevenharradine.locale
        locale_locales:
          - en_US.UTF-8
      - role: kbrebanov.java
        become: yes
        java_openjdk_use_ppa: no
      - role: ferrarimarco.xfce
        become: yes
      - role: ferrarimarco.eclipse
        become: yes
        java_openjdk_use_ppa: no
      - role: ferrarimarco.docker
        become: yes
        docker_compose_version: 1.17.1
        docker_apt_repository_section_name: stable edge
      - role: ferrarimarco.ruby
        become: yes
        ruby_version: 2.4.3
      - role: ferrarimarco.atom
        become: yes
        ferrarimarco_atom_become_users:
          - username: ferrarimarco
            atom_packages:
              - atom-beautify
              - autocomplete-plus
              - autocomplete-python
              - busy-signal
              - color-picker
              - file-icons
              - hyperclick
              - intentions
              - language-ansible
              - language-docker
              - language-powershell
              - linter
              - linter-ui-default
              - pigments
              - minimap
        ferrarimarco_atom_atom_version: 1.23.1
      - role: ferrarimarco.nano
        become: yes
      - role: ferrarimarco.bash-aliases
        bash_aliases:
          - { alias: "changelog-generator", command: 'docker run -it --rm -v "$(pwd)":/app prooph/github-changelog-generator' }
          - { alias: "docker-clean", command: 'docker run --rm -v /var/run/docker.sock:/var/run/docker.sock zzrot/docker-clean' }
          - { alias: "dockerfile-lint", command: 'echo "Linting Dockerfiles from $(pwd)"; find . -type f -iname "Dockerfile" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm -w="/mnt" lukasmartinelli/hadolint hadolint "$line"; docker run -v "$(pwd)":/mnt --rm -w="/mnt" redcoolbeans/dockerlint "$line"; done' }
          - { alias: "git-log1", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg1' }
          - { alias: "git-log2", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg2' }
          - { alias: "git-log3", command: 'docker run -it --rm -v "$(pwd)":/usr/src -w /usr/src --rm ferrarimarco/open-development-environment-git:1.0.1 lg3' }
          - { alias: "psscriptanalyzer", command: 'docker run -it --rm -v "$(pwd)":/powershell cvent/psscriptanalyzer' }
          - { alias: "shellcheck", command: 'echo "Linting shell scripts from $(pwd)"; find . -type f -iname "*.sh" | while read -r line; do echo "Linting $line"; docker run -v "$(pwd)":/mnt --rm koalaman/shellcheck-alpine "$line"; done'}
          - { alias: "pgadmin4", command: 'mkdir -p ~/.pgadmin4; name=pgadmin4; if [ ! "$(docker ps -q -f name=$name)" ]; then echo "Starting $name container"; docker run -d -p 5050:5050 -e "SERVER_MODE=False" --rm --name="$name" -v /home/vagrant/.pgadmin4:/data chorss/docker-pgadmin4; fi; sleep 5; xdg-open http://localhost:5050;'}
        become: yes
      - role: ferrarimarco.virtualbox
        become: yes
      - role: ferrarimarco.vagrant
        become: yes
        vagrant_download_url: "https://releases.hashicorp.com/vagrant/2.0.1/vagrant_2.0.1_x86_64.deb"
      - role: ferrarimarco.oracle-sql-developer
        become: yes
        ferrarimarco_oracle_sql_dev_archive_path: "/tmp/sqldeveloper-no-jre.zip"
      - role: chrisevett.inspec
        become: yes
        inspecVersion: 1.48.0
